package interfaces;

public interface AlgNumber {

    Integer ALG_INTEGER_INFINITE = 1000000000;
//    Double ALG_DOUBLE_POSITIVE_INFINITY = 1.0E9;
    Double ALG_DOUBLE_POSITIVE_INFINITY = Double.POSITIVE_INFINITY;
    Double ALG_DOUBLE_NEGATIVE_INFINITY = Double.NEGATIVE_INFINITY;
    Integer ALG_NIL_INTEGER = 1000000000;


}
